connections {
    my-vpn {
        version = 2
        vips = 0.0.0.0
        remote_addrs = 1.1.1.1
	proposals = aes256-sha512-prfsha512-modp2048, aes256-sha384-prfsha384-modp2048, aes256-sha256-prfsha256-modp2048

        local {
            auth = psk
        }
        
        remote {
            auth = psk
        }

        children {
            my-vpn-child {
                remote_ts = 172.10.0.0/24
                start_action = none
		esp_proposals = aes256-sha512-prfsha512-modp2048
            }
        }
    }
}

secrets {
    ike-my-vpn {
        secret = "SuperSecret"
    }
}
